//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSServices.WmsServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcsRequestInfo", Namespace="http://schemas.datacontract.org/2004/07/DC2")]
    [System.SerializableAttribute()]
    public partial class WcsRequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AdditionalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ContainerCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WcsRequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalInfo {
            get {
                return this.AdditionalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfoField, value) != true)) {
                    this.AdditionalInfoField = value;
                    this.RaisePropertyChanged("AdditionalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ContainerCodes {
            get {
                return this.ContainerCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerCodesField, value) != true)) {
                    this.ContainerCodesField = value;
                    this.RaisePropertyChanged("ContainerCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationUserCode {
            get {
                return this.LocationUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationUserCodeField, value) != true)) {
                    this.LocationUserCodeField = value;
                    this.RaisePropertyChanged("LocationUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WcsRequestId {
            get {
                return this.WcsRequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WcsRequestIdField, value) != true)) {
                    this.WcsRequestIdField = value;
                    this.RaisePropertyChanged("WcsRequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcsTaskInfo", Namespace="http://schemas.datacontract.org/2004/07/DC2")]
    [System.SerializableAttribute()]
    public partial class WcsTaskInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AdditionalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ContainerCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalInfo {
            get {
                return this.AdditionalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfoField, value) != true)) {
                    this.AdditionalInfoField = value;
                    this.RaisePropertyChanged("AdditionalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ContainerCodes {
            get {
                return this.ContainerCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerCodesField, value) != true)) {
                    this.ContainerCodesField = value;
                    this.RaisePropertyChanged("ContainerCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskCode {
            get {
                return this.TaskCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskCodeField, value) != true)) {
                    this.TaskCodeField = value;
                    this.RaisePropertyChanged("TaskCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskType {
            get {
                return this.TaskTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskTypeField, value) != true)) {
                    this.TaskTypeField = value;
                    this.RaisePropertyChanged("TaskType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IDataModelBase.InvokeMsg", Namespace="http://schemas.datacontract.org/2004/07/Wms")]
    [System.SerializableAttribute()]
    public partial class IDataModelBaseInvokeMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewEndPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewEndPoint {
            get {
                return this.NewEndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.NewEndPointField, value) != true)) {
                    this.NewEndPointField = value;
                    this.RaisePropertyChanged("NewEndPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcsRequestCurrentLocation", Namespace="http://schemas.datacontract.org/2004/07/DC2")]
    [System.SerializableAttribute()]
    public partial class WcsRequestCurrentLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AdditionalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ContainerCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentLocationLocationUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InOrOutStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WcsRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalInfo {
            get {
                return this.AdditionalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfoField, value) != true)) {
                    this.AdditionalInfoField = value;
                    this.RaisePropertyChanged("AdditionalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ContainerCodes {
            get {
                return this.ContainerCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerCodesField, value) != true)) {
                    this.ContainerCodesField = value;
                    this.RaisePropertyChanged("ContainerCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentLocationLocationUserCode {
            get {
                return this.CurrentLocationLocationUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentLocationLocationUserCodeField, value) != true)) {
                    this.CurrentLocationLocationUserCodeField = value;
                    this.RaisePropertyChanged("CurrentLocationLocationUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InOrOutStock {
            get {
                return this.InOrOutStockField;
            }
            set {
                if ((this.InOrOutStockField.Equals(value) != true)) {
                    this.InOrOutStockField = value;
                    this.RaisePropertyChanged("InOrOutStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationUserCode {
            get {
                return this.LocationUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationUserCodeField, value) != true)) {
                    this.LocationUserCodeField = value;
                    this.RaisePropertyChanged("LocationUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskCode {
            get {
                return this.TaskCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskCodeField, value) != true)) {
                    this.TaskCodeField = value;
                    this.RaisePropertyChanged("TaskCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskType {
            get {
                return this.TaskTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskTypeField, value) != true)) {
                    this.TaskTypeField = value;
                    this.RaisePropertyChanged("TaskType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WcsRequestId {
            get {
                return this.WcsRequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WcsRequestIdField, value) != true)) {
                    this.WcsRequestIdField = value;
                    this.RaisePropertyChanged("WcsRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WmsServices.IWcfWmsServiceForWcs")]
    public interface IWcfWmsServiceForWcs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfWmsServiceForWcs/Request", ReplyAction="http://tempuri.org/IWcfWmsServiceForWcs/RequestResponse")]
        void Request(WMSServices.WmsServices.WcsRequestInfo requestInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfWmsServiceForWcs/CompleteTask", ReplyAction="http://tempuri.org/IWcfWmsServiceForWcs/CompleteTaskResponse")]
        void CompleteTask(WMSServices.WmsServices.WcsTaskInfo taskInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfWmsServiceForWcs/RequestingTask", ReplyAction="http://tempuri.org/IWcfWmsServiceForWcs/RequestingTaskResponse")]
        WMSServices.WmsServices.IDataModelBaseInvokeMsg RequestingTask(WMSServices.WmsServices.WcsRequestInfo requestInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfWmsServiceForWcs/TaskErrorAndRequestNewEndPoint", ReplyAction="http://tempuri.org/IWcfWmsServiceForWcs/TaskErrorAndRequestNewEndPointResponse")]
        WMSServices.WmsServices.IDataModelBaseInvokeMsg TaskErrorAndRequestNewEndPoint(WMSServices.WmsServices.WcsRequestCurrentLocation wcsRequestCurrentLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfWmsServiceForWcs/CompletingTask", ReplyAction="http://tempuri.org/IWcfWmsServiceForWcs/CompletingTaskResponse")]
        WMSServices.WmsServices.IDataModelBaseInvokeMsg CompletingTask(WMSServices.WmsServices.WcsTaskInfo taskInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfWmsServiceForWcsChannel : WMSServices.WmsServices.IWcfWmsServiceForWcs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfWmsServiceForWcsClient : System.ServiceModel.ClientBase<WMSServices.WmsServices.IWcfWmsServiceForWcs>, WMSServices.WmsServices.IWcfWmsServiceForWcs {
        
        public WcfWmsServiceForWcsClient() {
        }
        
        public WcfWmsServiceForWcsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfWmsServiceForWcsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfWmsServiceForWcsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfWmsServiceForWcsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Request(WMSServices.WmsServices.WcsRequestInfo requestInfo) {
            base.Channel.Request(requestInfo);
        }
        
        public void CompleteTask(WMSServices.WmsServices.WcsTaskInfo taskInfo) {
            base.Channel.CompleteTask(taskInfo);
        }
        
        public WMSServices.WmsServices.IDataModelBaseInvokeMsg RequestingTask(WMSServices.WmsServices.WcsRequestInfo requestInfo) {
            return base.Channel.RequestingTask(requestInfo);
        }
        
        public WMSServices.WmsServices.IDataModelBaseInvokeMsg TaskErrorAndRequestNewEndPoint(WMSServices.WmsServices.WcsRequestCurrentLocation wcsRequestCurrentLocation) {
            return base.Channel.TaskErrorAndRequestNewEndPoint(wcsRequestCurrentLocation);
        }
        
        public WMSServices.WmsServices.IDataModelBaseInvokeMsg CompletingTask(WMSServices.WmsServices.WcsTaskInfo taskInfo) {
            return base.Channel.CompletingTask(taskInfo);
        }
    }
}
