//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.App.SingleForkCraneStatusDiagnoseMatedataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingleForkCraneStatusDiagnoseMatedataService.IMatedataService")]
    public interface IMatedataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatedataService/GetDiagnoseMatedatas", ReplyAction="http://tempuri.org/IMatedataService/GetDiagnoseMatedatasResponse")]
        string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatedataServiceChannel : Client.App.SingleForkCraneStatusDiagnoseMatedataService.IMatedataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatedataServiceClient : System.ServiceModel.ClientBase<Client.App.SingleForkCraneStatusDiagnoseMatedataService.IMatedataService>, Client.App.SingleForkCraneStatusDiagnoseMatedataService.IMatedataService {
        
        public MatedataServiceClient() {
        }
        
        public MatedataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatedataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatedataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatedataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo) {
            return base.Channel.GetDiagnoseMatedatas(minDataId, batchSize, appInfo);
        }
    }
}
