//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.App.RailGuidedVehicleDeviceServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RailGuidedVehicleDeviceServiceProxy.IRailGuidedVehicleService")]
    public interface IRailGuidedVehicleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatedataService/GetDiagnoseMatedatas", ReplyAction="http://tempuri.org/IMatedataService/GetDiagnoseMatedatasResponse")]
        string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRailGuidedVehicleService/Diagnose", ReplyAction="http://tempuri.org/IRailGuidedVehicleService/DiagnoseResponse")]
        string Diagnose(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRailGuidedVehicleService/GetAllStatus", ReplyAction="http://tempuri.org/IRailGuidedVehicleService/GetAllStatusResponse")]
        string GetAllStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRailGuidedVehicleService/Move", ReplyAction="http://tempuri.org/IRailGuidedVehicleService/MoveResponse")]
        void Move(string name, int station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRailGuidedVehicleService/Picking", ReplyAction="http://tempuri.org/IRailGuidedVehicleService/PickingResponse")]
        void Picking(string name, int direction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRailGuidedVehicleService/Putting", ReplyAction="http://tempuri.org/IRailGuidedVehicleService/PuttingResponse")]
        void Putting(string name, int direction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRailGuidedVehicleService/ClearTask", ReplyAction="http://tempuri.org/IRailGuidedVehicleService/ClearTaskResponse")]
        void ClearTask(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRailGuidedVehicleServiceChannel : Client.App.RailGuidedVehicleDeviceServiceProxy.IRailGuidedVehicleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RailGuidedVehicleServiceClient : System.ServiceModel.ClientBase<Client.App.RailGuidedVehicleDeviceServiceProxy.IRailGuidedVehicleService>, Client.App.RailGuidedVehicleDeviceServiceProxy.IRailGuidedVehicleService {
        
        public RailGuidedVehicleServiceClient() {
        }
        
        public RailGuidedVehicleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RailGuidedVehicleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RailGuidedVehicleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RailGuidedVehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo) {
            return base.Channel.GetDiagnoseMatedatas(minDataId, batchSize, appInfo);
        }
        
        public string Diagnose(string name) {
            return base.Channel.Diagnose(name);
        }
        
        public string GetAllStatus() {
            return base.Channel.GetAllStatus();
        }
        
        public void Move(string name, int station) {
            base.Channel.Move(name, station);
        }
        
        public void Picking(string name, int direction) {
            base.Channel.Picking(name, direction);
        }
        
        public void Putting(string name, int direction) {
            base.Channel.Putting(name, direction);
        }
        
        public void ClearTask(string name) {
            base.Channel.ClearTask(name);
        }
    }
}
