//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.App.ConveyorDeviceServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConveyorDeviceServiceProxy.IConveyorService")]
    public interface IConveyorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatedataService/GetDiagnoseMatedatas", ReplyAction="http://tempuri.org/IMatedataService/GetDiagnoseMatedatasResponse")]
        string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConveyorService/GetStatus", ReplyAction="http://tempuri.org/IConveyorService/GetStatusResponse")]
        string GetStatus(string deviceName, string fullTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConveyorService/ClearTask", ReplyAction="http://tempuri.org/IConveyorService/ClearTaskResponse")]
        void ClearTask(string deviceName, int equipmentTaskId, System.Nullable<int> atDBBlockIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConveyorService/DeleteTask", ReplyAction="http://tempuri.org/IConveyorService/DeleteTaskResponse")]
        void DeleteTask(string deviceName, int equipmentTaskId, System.Nullable<int> atDBBlockIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConveyorService/ClearLocationTask", ReplyAction="http://tempuri.org/IConveyorService/ClearLocationTaskResponse")]
        void ClearLocationTask(string deviceName, int posNo, int equipmentTaskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConveyorService/AddTask", ReplyAction="http://tempuri.org/IConveyorService/AddTaskResponse")]
        void AddTask(string deviceName, int equipmentTaskId, System.Nullable<int> routeNo, string startLocationUserCode, string endLocationUserCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConveyorServiceChannel : Client.App.ConveyorDeviceServiceProxy.IConveyorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConveyorServiceClient : System.ServiceModel.ClientBase<Client.App.ConveyorDeviceServiceProxy.IConveyorService>, Client.App.ConveyorDeviceServiceProxy.IConveyorService {
        
        public ConveyorServiceClient() {
        }
        
        public ConveyorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConveyorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConveyorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConveyorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo) {
            return base.Channel.GetDiagnoseMatedatas(minDataId, batchSize, appInfo);
        }
        
        public string GetStatus(string deviceName, string fullTypeName) {
            return base.Channel.GetStatus(deviceName, fullTypeName);
        }
        
        public void ClearTask(string deviceName, int equipmentTaskId, System.Nullable<int> atDBBlockIndex) {
            base.Channel.ClearTask(deviceName, equipmentTaskId, atDBBlockIndex);
        }
        
        public void DeleteTask(string deviceName, int equipmentTaskId, System.Nullable<int> atDBBlockIndex) {
            base.Channel.DeleteTask(deviceName, equipmentTaskId, atDBBlockIndex);
        }
        
        public void ClearLocationTask(string deviceName, int posNo, int equipmentTaskId) {
            base.Channel.ClearLocationTask(deviceName, posNo, equipmentTaskId);
        }
        
        public void AddTask(string deviceName, int equipmentTaskId, System.Nullable<int> routeNo, string startLocationUserCode, string endLocationUserCode) {
            base.Channel.AddTask(deviceName, equipmentTaskId, routeNo, startLocationUserCode, endLocationUserCode);
        }
    }
}
