//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEDServices.LEDService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LEDService.ILEDService")]
    public interface ILEDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILEDService/DeleteDynamicArea", ReplyAction="http://tempuri.org/ILEDService/DeleteDynamicAreaResponse")]
        void DeleteDynamicArea(string ledName, string areaName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILEDService/SendDynamicAreaContents", ReplyAction="http://tempuri.org/ILEDService/SendDynamicAreaContentsResponse")]
        void SendDynamicAreaContents(string ledName, string areaName, string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILEDServiceChannel : LEDServices.LEDService.ILEDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LEDServiceClient : System.ServiceModel.ClientBase<LEDServices.LEDService.ILEDService>, LEDServices.LEDService.ILEDService {
        
        public LEDServiceClient() {
        }
        
        public LEDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LEDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LEDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LEDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteDynamicArea(string ledName, string areaName) {
            base.Channel.DeleteDynamicArea(ledName, areaName);
        }
        
        public void SendDynamicAreaContents(string ledName, string areaName, string text) {
            base.Channel.SendDynamicAreaContents(ledName, areaName, text);
        }
    }
}
