//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.WebUIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebUIServiceResult", Namespace="http://schemas.datacontract.org/2004/07/Wcs.Services.Wcf.WebUI")]
    [System.SerializableAttribute()]
    public partial class WebUIServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebUIService.IWebUIService")]
    public interface IWebUIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/GetConveyorCurrentTasks", ReplyAction="http://tempuri.org/IWebUIService/GetConveyorCurrentTasksResponse")]
        WebUI.WebUIService.WebUIServiceResult GetConveyorCurrentTasks(string deviceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/GetConveyorStatus", ReplyAction="http://tempuri.org/IWebUIService/GetConveyorStatusResponse")]
        WebUI.WebUIService.WebUIServiceResult GetConveyorStatus(string deviceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/GetConveyorStatusFromLastReceivedPackage", ReplyAction="http://tempuri.org/IWebUIService/GetConveyorStatusFromLastReceivedPackageResponse" +
            "")]
        WebUI.WebUIService.WebUIServiceResult GetConveyorStatusFromLastReceivedPackage(string deviceName, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/GetCraneStatus", ReplyAction="http://tempuri.org/IWebUIService/GetCraneStatusResponse")]
        WebUI.WebUIService.WebUIServiceResult GetCraneStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/GetTasks", ReplyAction="http://tempuri.org/IWebUIService/GetTasksResponse")]
        WebUI.WebUIService.WebUIServiceResult GetTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/GetTaskDetails", ReplyAction="http://tempuri.org/IWebUIService/GetTaskDetailsResponse")]
        WebUI.WebUIService.WebUIServiceResult GetTaskDetails(string taskNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/SuspendTask", ReplyAction="http://tempuri.org/IWebUIService/SuspendTaskResponse")]
        WebUI.WebUIService.WebUIServiceResult SuspendTask(string taskNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/CompleteTask", ReplyAction="http://tempuri.org/IWebUIService/CompleteTaskResponse")]
        WebUI.WebUIService.WebUIServiceResult CompleteTask(string ObjectType, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/CancelTask", ReplyAction="http://tempuri.org/IWebUIService/CancelTaskResponse")]
        WebUI.WebUIService.WebUIServiceResult CancelTask(string taskNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/ResumeTask", ReplyAction="http://tempuri.org/IWebUIService/ResumeTaskResponse")]
        WebUI.WebUIService.WebUIServiceResult ResumeTask(string taskNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/ResumeTaskWithCurrentLocation", ReplyAction="http://tempuri.org/IWebUIService/ResumeTaskWithCurrentLocationResponse")]
        WebUI.WebUIService.WebUIServiceResult ResumeTaskWithCurrentLocation(string taskNo, string currentLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebUIService/GetDevicesConnectionStatus", ReplyAction="http://tempuri.org/IWebUIService/GetDevicesConnectionStatusResponse")]
        WebUI.WebUIService.WebUIServiceResult GetDevicesConnectionStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebUIServiceChannel : WebUI.WebUIService.IWebUIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebUIServiceClient : System.ServiceModel.ClientBase<WebUI.WebUIService.IWebUIService>, WebUI.WebUIService.IWebUIService {
        
        public WebUIServiceClient() {
        }
        
        public WebUIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebUIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebUIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebUIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebUI.WebUIService.WebUIServiceResult GetConveyorCurrentTasks(string deviceName) {
            return base.Channel.GetConveyorCurrentTasks(deviceName);
        }
        
        public WebUI.WebUIService.WebUIServiceResult GetConveyorStatus(string deviceName) {
            return base.Channel.GetConveyorStatus(deviceName);
        }
        
        public WebUI.WebUIService.WebUIServiceResult GetConveyorStatusFromLastReceivedPackage(string deviceName, string type) {
            return base.Channel.GetConveyorStatusFromLastReceivedPackage(deviceName, type);
        }
        
        public WebUI.WebUIService.WebUIServiceResult GetCraneStatus() {
            return base.Channel.GetCraneStatus();
        }
        
        public WebUI.WebUIService.WebUIServiceResult GetTasks() {
            return base.Channel.GetTasks();
        }
        
        public WebUI.WebUIService.WebUIServiceResult GetTaskDetails(string taskNo) {
            return base.Channel.GetTaskDetails(taskNo);
        }
        
        public WebUI.WebUIService.WebUIServiceResult SuspendTask(string taskNo) {
            return base.Channel.SuspendTask(taskNo);
        }
        
        public WebUI.WebUIService.WebUIServiceResult CompleteTask(string ObjectType, int id) {
            return base.Channel.CompleteTask(ObjectType, id);
        }
        
        public WebUI.WebUIService.WebUIServiceResult CancelTask(string taskNo) {
            return base.Channel.CancelTask(taskNo);
        }
        
        public WebUI.WebUIService.WebUIServiceResult ResumeTask(string taskNo) {
            return base.Channel.ResumeTask(taskNo);
        }
        
        public WebUI.WebUIService.WebUIServiceResult ResumeTaskWithCurrentLocation(string taskNo, string currentLocation) {
            return base.Channel.ResumeTaskWithCurrentLocation(taskNo, currentLocation);
        }
        
        public WebUI.WebUIService.WebUIServiceResult GetDevicesConnectionStatus() {
            return base.Channel.GetDevicesConnectionStatus();
        }
    }
}
