//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CraneInfo", Namespace="http://schemas.datacontract.org/2004/07/CraneService.TwoForksCrane")]
    [System.SerializableAttribute()]
    public partial class CraneInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxColumn {
            get {
                return this.MaxColumnField;
            }
            set {
                if ((this.MaxColumnField.Equals(value) != true)) {
                    this.MaxColumnField = value;
                    this.RaisePropertyChanged("MaxColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxLevel {
            get {
                return this.MaxLevelField;
            }
            set {
                if ((this.MaxLevelField.Equals(value) != true)) {
                    this.MaxLevelField = value;
                    this.RaisePropertyChanged("MaxLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinColumn {
            get {
                return this.MinColumnField;
            }
            set {
                if ((this.MinColumnField.Equals(value) != true)) {
                    this.MinColumnField = value;
                    this.RaisePropertyChanged("MinColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinLevel {
            get {
                return this.MinLevelField;
            }
            set {
                if ((this.MinLevelField.Equals(value) != true)) {
                    this.MinLevelField = value;
                    this.RaisePropertyChanged("MinLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LA", Namespace="http://schemas.datacontract.org/2004/07/CraneService.TwoForksCrane")]
    [System.SerializableAttribute()]
    public partial class LA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorSolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.CraneEvent EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkHorizontalPosition Fork1HorizontalPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkStatus Fork1StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkHorizontalPosition Fork2HorizontalPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkStatus Fork2StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkVerticalPosition ForkVerticalPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LockerIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LockerUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.CraneStatus StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AtStation {
            get {
                return this.AtStationField;
            }
            set {
                if ((this.AtStationField.Equals(value) != true)) {
                    this.AtStationField = value;
                    this.RaisePropertyChanged("AtStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorName {
            get {
                return this.ErrorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorNameField, value) != true)) {
                    this.ErrorNameField = value;
                    this.RaisePropertyChanged("ErrorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorSolution {
            get {
                return this.ErrorSolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorSolutionField, value) != true)) {
                    this.ErrorSolutionField = value;
                    this.RaisePropertyChanged("ErrorSolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.CraneEvent Event {
            get {
                return this.EventField;
            }
            set {
                if ((this.EventField.Equals(value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkHorizontalPosition Fork1HorizontalPosition {
            get {
                return this.Fork1HorizontalPositionField;
            }
            set {
                if ((this.Fork1HorizontalPositionField.Equals(value) != true)) {
                    this.Fork1HorizontalPositionField = value;
                    this.RaisePropertyChanged("Fork1HorizontalPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkStatus Fork1Status {
            get {
                return this.Fork1StatusField;
            }
            set {
                if ((this.Fork1StatusField.Equals(value) != true)) {
                    this.Fork1StatusField = value;
                    this.RaisePropertyChanged("Fork1Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkHorizontalPosition Fork2HorizontalPosition {
            get {
                return this.Fork2HorizontalPositionField;
            }
            set {
                if ((this.Fork2HorizontalPositionField.Equals(value) != true)) {
                    this.Fork2HorizontalPositionField = value;
                    this.RaisePropertyChanged("Fork2HorizontalPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkStatus Fork2Status {
            get {
                return this.Fork2StatusField;
            }
            set {
                if ((this.Fork2StatusField.Equals(value) != true)) {
                    this.Fork2StatusField = value;
                    this.RaisePropertyChanged("Fork2Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkVerticalPosition ForkVerticalPosition {
            get {
                return this.ForkVerticalPositionField;
            }
            set {
                if ((this.ForkVerticalPositionField.Equals(value) != true)) {
                    this.ForkVerticalPositionField = value;
                    this.RaisePropertyChanged("ForkVerticalPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockerIp {
            get {
                return this.LockerIpField;
            }
            set {
                if ((object.ReferenceEquals(this.LockerIpField, value) != true)) {
                    this.LockerIpField = value;
                    this.RaisePropertyChanged("LockerIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockerUser {
            get {
                return this.LockerUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LockerUserField, value) != true)) {
                    this.LockerUserField = value;
                    this.RaisePropertyChanged("LockerUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.CraneStatus State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIdField, value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserColumn {
            get {
                return this.UserColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.UserColumnField, value) != true)) {
                    this.UserColumnField = value;
                    this.RaisePropertyChanged("UserColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLevelField, value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForkDirection", Namespace="http://schemas.datacontract.org/2004/07/Wcs.DefaultImpls.Crane")]
    public enum ForkDirection : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Left = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Right = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Left2 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Right2 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CraneEvent", Namespace="http://schemas.datacontract.org/2004/07/Wcs.DefaultImpls.Crane")]
    public enum CraneEvent : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Initialized = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeginRunning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeginPickup = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndPickup = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeginPutin = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndPutin = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmergencyStop = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedWithError = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BackToTheOrigin = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForkHorizontalPosition", Namespace="http://schemas.datacontract.org/2004/07/Wcs.DefaultImpls.Crane")]
    public enum ForkHorizontalPosition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Center = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Left = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LeftLimit = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Right = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RightLimit = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E6 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E7 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E8 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E9 = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForkStatus", Namespace="http://schemas.datacontract.org/2004/07/Wcs.DefaultImpls.TwoForksCrane")]
    public enum ForkStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        初始化 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        无货待命 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        有货待命 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        故障 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForkVerticalPosition", Namespace="http://schemas.datacontract.org/2004/07/Wcs.DefaultImpls.Crane")]
    public enum ForkVerticalPosition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Middle = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Top = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bottom = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknow = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CraneStatus", Namespace="http://schemas.datacontract.org/2004/07/Wcs.DefaultImpls.Crane")]
    public enum CraneStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Initialized = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BackToTheOrigin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        无货待命 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        有货待命 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        无货运行 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        有货运行 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pickup = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Putin = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlarmAndShutdown = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResetAlarm = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        奇怪的状态 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disconnected = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManualMode = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TwoForksCraneService.ITwoForksCraneService")]
    public interface ITwoForksCraneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/LoadCraneInfos", ReplyAction="http://tempuri.org/ITwoForksCraneService/LoadCraneInfosResponse")]
        Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.CraneInfo[] LoadCraneInfos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/ReadStatus", ReplyAction="http://tempuri.org/ITwoForksCraneService/ReadStatusResponse")]
        System.Collections.Generic.Dictionary<string, Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.LA> ReadStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/BackToTheOrigin", ReplyAction="http://tempuri.org/ITwoForksCraneService/BackToTheOriginResponse")]
        void BackToTheOrigin(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/EmergencyStop", ReplyAction="http://tempuri.org/ITwoForksCraneService/EmergencyStopResponse")]
        void EmergencyStop(string craneName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/CancelEmergencyStop", ReplyAction="http://tempuri.org/ITwoForksCraneService/CancelEmergencyStopResponse")]
        void CancelEmergencyStop(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Move", ReplyAction="http://tempuri.org/ITwoForksCraneService/MoveResponse")]
        void Move(string craneName, string userName, string ipAddress, int userColumn, int userLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/MoveByForkDirection", ReplyAction="http://tempuri.org/ITwoForksCraneService/MoveByForkDirectionResponse")]
        void MoveByForkDirection(string craneName, string userName, string ipAddress, int userColumn, int userLevel, Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection forkDirection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/MoveByForkDirectionAndFork", ReplyAction="http://tempuri.org/ITwoForksCraneService/MoveByForkDirectionAndForkResponse")]
        void MoveByForkDirectionAndFork(string craneName, string userName, string ipAddress, string userCode, bool alignToFork1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Pick", ReplyAction="http://tempuri.org/ITwoForksCraneService/PickResponse")]
        void Pick(string craneName, string userName, string ipAddress, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork1Direction, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork2Direction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Putdown", ReplyAction="http://tempuri.org/ITwoForksCraneService/PutdownResponse")]
        void Putdown(string craneName, string userName, string ipAddress, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork1Direction, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork2Direction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Lock", ReplyAction="http://tempuri.org/ITwoForksCraneService/LockResponse")]
        void Lock(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Unlock", ReplyAction="http://tempuri.org/ITwoForksCraneService/UnlockResponse")]
        void Unlock(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Up", ReplyAction="http://tempuri.org/ITwoForksCraneService/UpResponse")]
        void Up(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Down", ReplyAction="http://tempuri.org/ITwoForksCraneService/DownResponse")]
        void Down(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Forward", ReplyAction="http://tempuri.org/ITwoForksCraneService/ForwardResponse")]
        void Forward(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/Back", ReplyAction="http://tempuri.org/ITwoForksCraneService/BackResponse")]
        void Back(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwoForksCraneService/ResetWarn", ReplyAction="http://tempuri.org/ITwoForksCraneService/ResetWarnResponse")]
        void ResetWarn(string craneName, string userName, string ipAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITwoForksCraneServiceChannel : Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ITwoForksCraneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwoForksCraneServiceClient : System.ServiceModel.ClientBase<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ITwoForksCraneService>, Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ITwoForksCraneService {
        
        public TwoForksCraneServiceClient() {
        }
        
        public TwoForksCraneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwoForksCraneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoForksCraneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoForksCraneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.CraneInfo[] LoadCraneInfos() {
            return base.Channel.LoadCraneInfos();
        }
        
        public System.Collections.Generic.Dictionary<string, Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.LA> ReadStatus() {
            return base.Channel.ReadStatus();
        }
        
        public void BackToTheOrigin(string craneName, string userName, string ipAddress) {
            base.Channel.BackToTheOrigin(craneName, userName, ipAddress);
        }
        
        public void EmergencyStop(string craneName) {
            base.Channel.EmergencyStop(craneName);
        }
        
        public void CancelEmergencyStop(string craneName, string userName, string ipAddress) {
            base.Channel.CancelEmergencyStop(craneName, userName, ipAddress);
        }
        
        public void Move(string craneName, string userName, string ipAddress, int userColumn, int userLevel) {
            base.Channel.Move(craneName, userName, ipAddress, userColumn, userLevel);
        }
        
        public void MoveByForkDirection(string craneName, string userName, string ipAddress, int userColumn, int userLevel, Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection forkDirection) {
            base.Channel.MoveByForkDirection(craneName, userName, ipAddress, userColumn, userLevel, forkDirection);
        }
        
        public void MoveByForkDirectionAndFork(string craneName, string userName, string ipAddress, string userCode, bool alignToFork1) {
            base.Channel.MoveByForkDirectionAndFork(craneName, userName, ipAddress, userCode, alignToFork1);
        }
        
        public void Pick(string craneName, string userName, string ipAddress, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork1Direction, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork2Direction) {
            base.Channel.Pick(craneName, userName, ipAddress, fork1Direction, fork2Direction);
        }
        
        public void Putdown(string craneName, string userName, string ipAddress, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork1Direction, System.Nullable<Wcs.App.Plugins.TwoForksCraneManualClient.TwoForksCraneService.ForkDirection> fork2Direction) {
            base.Channel.Putdown(craneName, userName, ipAddress, fork1Direction, fork2Direction);
        }
        
        public void Lock(string craneName, string userName, string ipAddress) {
            base.Channel.Lock(craneName, userName, ipAddress);
        }
        
        public void Unlock(string craneName, string userName, string ipAddress) {
            base.Channel.Unlock(craneName, userName, ipAddress);
        }
        
        public void Up(string craneName, string userName, string ipAddress) {
            base.Channel.Up(craneName, userName, ipAddress);
        }
        
        public void Down(string craneName, string userName, string ipAddress) {
            base.Channel.Down(craneName, userName, ipAddress);
        }
        
        public void Forward(string craneName, string userName, string ipAddress) {
            base.Channel.Forward(craneName, userName, ipAddress);
        }
        
        public void Back(string craneName, string userName, string ipAddress) {
            base.Channel.Back(craneName, userName, ipAddress);
        }
        
        public void ResetWarn(string craneName, string userName, string ipAddress) {
            base.Channel.ResetWarn(craneName, userName, ipAddress);
        }
    }
}
