//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.App.CraneDeviceServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CraneInfo", Namespace="http://schemas.datacontract.org/2004/07/DeviceServer.Services.SingleForkCraneDevi" +
        "ceService")]
    [System.SerializableAttribute()]
    public partial class CraneInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxColumn {
            get {
                return this.MaxColumnField;
            }
            set {
                if ((this.MaxColumnField.Equals(value) != true)) {
                    this.MaxColumnField = value;
                    this.RaisePropertyChanged("MaxColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxLevel {
            get {
                return this.MaxLevelField;
            }
            set {
                if ((this.MaxLevelField.Equals(value) != true)) {
                    this.MaxLevelField = value;
                    this.RaisePropertyChanged("MaxLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinColumn {
            get {
                return this.MinColumnField;
            }
            set {
                if ((this.MinColumnField.Equals(value) != true)) {
                    this.MinColumnField = value;
                    this.RaisePropertyChanged("MinColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinLevel {
            get {
                return this.MinLevelField;
            }
            set {
                if ((this.MinLevelField.Equals(value) != true)) {
                    this.MinLevelField = value;
                    this.RaisePropertyChanged("MinLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LA", Namespace="http://schemas.datacontract.org/2004/07/DeviceServer.Services.SingleForkCraneDevi" +
        "ceService")]
    [System.SerializableAttribute()]
    public partial class LA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorSolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.DefaultImpls.Crane.CraneEvent EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.DefaultImpls.Crane.ForkHorizontalPosition ForkHorizontalPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.DefaultImpls.Crane.ForkVerticalPosition ForkVerticalPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LockerIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LockerUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wcs.DefaultImpls.Crane.CraneStatus StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AtStation {
            get {
                return this.AtStationField;
            }
            set {
                if ((this.AtStationField.Equals(value) != true)) {
                    this.AtStationField = value;
                    this.RaisePropertyChanged("AtStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorName {
            get {
                return this.ErrorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorNameField, value) != true)) {
                    this.ErrorNameField = value;
                    this.RaisePropertyChanged("ErrorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorSolution {
            get {
                return this.ErrorSolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorSolutionField, value) != true)) {
                    this.ErrorSolutionField = value;
                    this.RaisePropertyChanged("ErrorSolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.DefaultImpls.Crane.CraneEvent Event {
            get {
                return this.EventField;
            }
            set {
                if ((this.EventField.Equals(value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.DefaultImpls.Crane.ForkHorizontalPosition ForkHorizontalPosition {
            get {
                return this.ForkHorizontalPositionField;
            }
            set {
                if ((this.ForkHorizontalPositionField.Equals(value) != true)) {
                    this.ForkHorizontalPositionField = value;
                    this.RaisePropertyChanged("ForkHorizontalPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.DefaultImpls.Crane.ForkVerticalPosition ForkVerticalPosition {
            get {
                return this.ForkVerticalPositionField;
            }
            set {
                if ((this.ForkVerticalPositionField.Equals(value) != true)) {
                    this.ForkVerticalPositionField = value;
                    this.RaisePropertyChanged("ForkVerticalPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockerIp {
            get {
                return this.LockerIpField;
            }
            set {
                if ((object.ReferenceEquals(this.LockerIpField, value) != true)) {
                    this.LockerIpField = value;
                    this.RaisePropertyChanged("LockerIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockerUser {
            get {
                return this.LockerUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LockerUserField, value) != true)) {
                    this.LockerUserField = value;
                    this.RaisePropertyChanged("LockerUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcs.DefaultImpls.Crane.CraneStatus State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIdField, value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserColumn {
            get {
                return this.UserColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.UserColumnField, value) != true)) {
                    this.UserColumnField = value;
                    this.RaisePropertyChanged("UserColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLevelField, value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CraneDeviceServiceProxy.ICraneService")]
    public interface ICraneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatedataService/GetDiagnoseMatedatas", ReplyAction="http://tempuri.org/IMatedataService/GetDiagnoseMatedatasResponse")]
        string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/LoadCraneInfos", ReplyAction="http://tempuri.org/ICraneService/LoadCraneInfosResponse")]
        Client.App.CraneDeviceServiceProxy.CraneInfo[] LoadCraneInfos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/ReadStatus", ReplyAction="http://tempuri.org/ICraneService/ReadStatusResponse")]
        System.Collections.Generic.Dictionary<string, Client.App.CraneDeviceServiceProxy.LA> ReadStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/BackToTheOrigin", ReplyAction="http://tempuri.org/ICraneService/BackToTheOriginResponse")]
        void BackToTheOrigin(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/EmergencyStop", ReplyAction="http://tempuri.org/ICraneService/EmergencyStopResponse")]
        void EmergencyStop(string craneName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/CancelEmergencyStop", ReplyAction="http://tempuri.org/ICraneService/CancelEmergencyStopResponse")]
        void CancelEmergencyStop(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Move", ReplyAction="http://tempuri.org/ICraneService/MoveResponse")]
        void Move(string craneName, string userName, string ipAddress, int userColumn, int userLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Pick", ReplyAction="http://tempuri.org/ICraneService/PickResponse")]
        void Pick(string craneName, string userName, string ipAddress, Wcs.DefaultImpls.Crane.ForkDirection forkDirection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Putdown", ReplyAction="http://tempuri.org/ICraneService/PutdownResponse")]
        void Putdown(string craneName, string userName, string ipAddress, Wcs.DefaultImpls.Crane.ForkDirection forkDirection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Lock", ReplyAction="http://tempuri.org/ICraneService/LockResponse")]
        void Lock(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Unlock", ReplyAction="http://tempuri.org/ICraneService/UnlockResponse")]
        void Unlock(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Up", ReplyAction="http://tempuri.org/ICraneService/UpResponse")]
        void Up(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Down", ReplyAction="http://tempuri.org/ICraneService/DownResponse")]
        void Down(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Forward", ReplyAction="http://tempuri.org/ICraneService/ForwardResponse")]
        void Forward(string craneName, string userName, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICraneService/Back", ReplyAction="http://tempuri.org/ICraneService/BackResponse")]
        void Back(string craneName, string userName, string ipAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICraneServiceChannel : Client.App.CraneDeviceServiceProxy.ICraneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CraneServiceClient : System.ServiceModel.ClientBase<Client.App.CraneDeviceServiceProxy.ICraneService>, Client.App.CraneDeviceServiceProxy.ICraneService {
        
        public CraneServiceClient() {
        }
        
        public CraneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CraneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CraneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CraneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDiagnoseMatedatas(int minDataId, int batchSize, string appInfo) {
            return base.Channel.GetDiagnoseMatedatas(minDataId, batchSize, appInfo);
        }
        
        public Client.App.CraneDeviceServiceProxy.CraneInfo[] LoadCraneInfos() {
            return base.Channel.LoadCraneInfos();
        }
        
        public System.Collections.Generic.Dictionary<string, Client.App.CraneDeviceServiceProxy.LA> ReadStatus() {
            return base.Channel.ReadStatus();
        }
        
        public void BackToTheOrigin(string craneName, string userName, string ipAddress) {
            base.Channel.BackToTheOrigin(craneName, userName, ipAddress);
        }
        
        public void EmergencyStop(string craneName) {
            base.Channel.EmergencyStop(craneName);
        }
        
        public void CancelEmergencyStop(string craneName, string userName, string ipAddress) {
            base.Channel.CancelEmergencyStop(craneName, userName, ipAddress);
        }
        
        public void Move(string craneName, string userName, string ipAddress, int userColumn, int userLevel) {
            base.Channel.Move(craneName, userName, ipAddress, userColumn, userLevel);
        }
        
        public void Pick(string craneName, string userName, string ipAddress, Wcs.DefaultImpls.Crane.ForkDirection forkDirection) {
            base.Channel.Pick(craneName, userName, ipAddress, forkDirection);
        }
        
        public void Putdown(string craneName, string userName, string ipAddress, Wcs.DefaultImpls.Crane.ForkDirection forkDirection) {
            base.Channel.Putdown(craneName, userName, ipAddress, forkDirection);
        }
        
        public void Lock(string craneName, string userName, string ipAddress) {
            base.Channel.Lock(craneName, userName, ipAddress);
        }
        
        public void Unlock(string craneName, string userName, string ipAddress) {
            base.Channel.Unlock(craneName, userName, ipAddress);
        }
        
        public void Up(string craneName, string userName, string ipAddress) {
            base.Channel.Up(craneName, userName, ipAddress);
        }
        
        public void Down(string craneName, string userName, string ipAddress) {
            base.Channel.Down(craneName, userName, ipAddress);
        }
        
        public void Forward(string craneName, string userName, string ipAddress) {
            base.Channel.Forward(craneName, userName, ipAddress);
        }
        
        public void Back(string craneName, string userName, string ipAddress) {
            base.Channel.Back(craneName, userName, ipAddress);
        }
    }
}
